name: CI

on: [pull_request]

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          jobSummary: true
          args: --insecure --verbose --no-progress './**/*.md' './**/*.html' './**/*.njk' './**/*.yaml'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: yarn install
      - run: yarn lint-check
