name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      uses: peter-evans/link-checker@v1.1.0
      with:
        args: -v -r *

